//
// ─── X-MACRO LIST OF 8086-80386 MNEMONICS ──────────────────────────────────────
//
// This file is designed to be #included multiple times, once to create the
// ASM_MNEMONIC enum and once to create the asm_mnemonics[] table.
//
// The MNEMONIC and MNEMONIC_0F macros will be defined by the including header.
//
// Definitions (Flags):
// FLG_ARITH = FLG_O | FLG_S | FLG_Z | FLG_A | FLG_P | FLG_C
// FLG_LOGIC = FLG_LOGIC
//
// Definitions (Operand Arrays):

#define OPCODE_EXPANDER(x, y) {x,y}
#define OPS_EXPANDER(a) {a}

//
// ─── ADD (0x00 - 0x05) ────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_ADD_RM8_R8, "add", PF_NONE, OPCODE_EXPANDER({0x00, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add r8 to r/m8")
MNEMONIC(MNEM_ADD_RM16_R16, "add", PF_NONE, OPCODE_EXPANDER({0x01, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add r16 to r/m16")
MNEMONIC(MNEM_ADD_RM32_R32, "add", PF_66, OPCODE_EXPANDER({0x01, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add r32 to r/m32")
MNEMONIC(MNEM_ADD_R8_RM8, "add", PF_NONE, OPCODE_EXPANDER({0x02, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add r/m8 to r8")
MNEMONIC(MNEM_ADD_R16_RM16, "add", PF_NONE, OPCODE_EXPANDER({0x03, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add r/m16 to r16")
MNEMONIC(MNEM_ADD_R32_RM32, "add", PF_66, OPCODE_EXPANDER({0x03, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add r/m32 to r32")
MNEMONIC(MNEM_ADD_AL_IMM8, "add", PF_NONE, OPCODE_EXPANDER({0x04, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add imm8 to AL")
MNEMONIC(MNEM_ADD_AX_IMM16, "add", PF_NONE, OPCODE_EXPANDER({0x05, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add imm16 to AX")
MNEMONIC(MNEM_ADD_EAX_IMM32, "add", PF_66, OPCODE_EXPANDER({0x05, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add imm32 to EAX")

// ─── PUSH/POP SEGMENT (0x06 - 0x1F) ───────────────────────────────────────────
//
MNEMONIC(MNEM_PUSH_ES, "push", PF_NONE, OPCODE_EXPANDER({0x06, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_SEG), OPN_ONE, SZ_16BIT, RF_ES, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push ES")
MNEMONIC(MNEM_POP_ES, "pop", PF_NONE, OPCODE_EXPANDER({0x07, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_SEG), OPN_ONE, SZ_16BIT, RF_ES, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop ES")
MNEMONIC(MNEM_PUSH_CS, "push", PF_NONE, OPCODE_EXPANDER({0x0E, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_SEG), OPN_ONE, SZ_16BIT, RF_CS, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push CS")
MNEMONIC(MNEM_PUSH_SS, "push", PF_NONE, OPCODE_EXPANDER({0x16, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_SEG), OPN_ONE, SZ_16BIT, RF_SS, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push SS")
MNEMONIC(MNEM_POP_SS, "pop", PF_NONE, OPCODE_EXPANDER({0x17, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_SEG), OPN_ONE, SZ_16BIT, RF_SS, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop SS")
MNEMONIC(MNEM_PUSH_DS, "push", PF_NONE, OPCODE_EXPANDER({0x1E, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_SEG), OPN_ONE, SZ_16BIT, RF_DS, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push DS")
MNEMONIC(MNEM_POP_DS, "pop", PF_NONE, OPCODE_EXPANDER({0x1F, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_SEG), OPN_ONE, SZ_16BIT, RF_DS, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "a")

//
// ─── OR (0x08 - 0x0D) ─────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_OR_RM8_R8, "or", PF_NONE, OPCODE_EXPANDER({0x08, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or r8 to r/m8")
MNEMONIC(MNEM_OR_RM16_R16, "or", PF_NONE, OPCODE_EXPANDER({0x09, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or r16 to r/m16")
MNEMONIC(MNEM_OR_RM32_R32, "or", PF_66, OPCODE_EXPANDER({0x09, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or r32 to r/m32")
MNEMONIC(MNEM_OR_R8_RM8, "or", PF_NONE, OPCODE_EXPANDER({0x0A, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or r/m8 to r8")
MNEMONIC(MNEM_OR_R16_RM16, "or", PF_NONE, OPCODE_EXPANDER({0x0B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or r/m16 to r16")
MNEMONIC(MNEM_OR_R32_RM32, "or", PF_66, OPCODE_EXPANDER({0x0B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or r/m32 to r32")
MNEMONIC(MNEM_OR_AL_IMM8, "or", PF_NONE, OPCODE_EXPANDER({0x0C, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or imm8 to AL")
MNEMONIC(MNEM_OR_AX_IMM16, "or", PF_NONE, OPCODE_EXPANDER({0x0D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or imm16 to AX")
MNEMONIC(MNEM_OR_EAX_IMM32, "or", PF_66, OPCODE_EXPANDER({0x0D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, (FLG_ARITH), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or imm32 to EAX")

//
// ─── ADC (0x10 - 0x15) ────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_ADC_RM8_R8, "adc", PF_NONE, OPCODE_EXPANDER({0x10, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry r8 to r/m8")
MNEMONIC(MNEM_ADC_RM16_R16, "adc", PF_NONE, OPCODE_EXPANDER({0x11, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry r16 to r/m16")
MNEMONIC(MNEM_ADC_RM32_R32, "adc", PF_66, OPCODE_EXPANDER({0x11, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry r32 to r/m32")
MNEMONIC(MNEM_ADC_R8_RM8, "adc", PF_NONE, OPCODE_EXPANDER({0x12, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry r/m8 to r8")
MNEMONIC(MNEM_ADC_R16_RM16, "adc", PF_NONE, OPCODE_EXPANDER({0x13, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry r/m16 to r16")
MNEMONIC(MNEM_ADC_R32_RM32, "adc", PF_66, OPCODE_EXPANDER({0x13, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry r/m32 to r32")
MNEMONIC(MNEM_ADC_AL_IMM8, "adc", PF_NONE, OPCODE_EXPANDER({0x14, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry imm8 to AL")
MNEMONIC(MNEM_ADC_AX_IMM16, "adc", PF_NONE, OPCODE_EXPANDER({0x15, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry imm16 to AX")
MNEMONIC(MNEM_ADC_EAX_IMM32, "adc", PF_66, OPCODE_EXPANDER({0x15, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry imm32 to EAX")

//
// ─── SBB (0x18 - 0x1D) ────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_SBB_RM8_R8, "sbb", PF_NONE, OPCODE_EXPANDER({0x18, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow r8 from r/m8")
MNEMONIC(MNEM_SBB_RM16_R16, "sbb", PF_NONE, OPCODE_EXPANDER({0x19, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow r16 from r/m16")
MNEMONIC(MNEM_SBB_RM32_R32, "sbb", PF_66, OPCODE_EXPANDER({0x19, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow r32 from r/m32")
MNEMONIC(MNEM_SBB_R8_RM8, "sbb", PF_NONE, OPCODE_EXPANDER({0x1A, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow r/m8 from r8")
MNEMONIC(MNEM_SBB_R16_RM16, "sbb", PF_NONE, OPCODE_EXPANDER({0x1B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow r/m16 from r16")
MNEMONIC(MNEM_SBB_R32_RM32, "sbb", PF_66, OPCODE_EXPANDER({0x1B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow r/m32 from r32")
MNEMONIC(MNEM_SBB_AL_IMM8, "sbb", PF_NONE, OPCODE_EXPANDER({0x1C, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow imm8 from AL")
MNEMONIC(MNEM_SBB_AX_IMM16, "sbb", PF_NONE, OPCODE_EXPANDER({0x1D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow imm16 from AX")
MNEMONIC(MNEM_SBB_EAX_IMM32, "sbb", PF_66, OPCODE_EXPANDER({0x1D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow imm32 from EAX")

//
// ─── AND (0x20 - 0x25) ────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_AND_RM8_R8, "and", PF_NONE, OPCODE_EXPANDER({0x20, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And r8 to r/m8")
MNEMONIC(MNEM_AND_RM16_R16, "and", PF_NONE, OPCODE_EXPANDER({0x21, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And r16 to r/m16")
MNEMONIC(MNEM_AND_RM32_R32, "and", PF_66, OPCODE_EXPANDER({0x21, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And r32 to r/m32")
MNEMONIC(MNEM_AND_R8_RM8, "and", PF_NONE, OPCODE_EXPANDER({0x22, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And r/m8 to r8")
MNEMONIC(MNEM_AND_R16_RM16, "and", PF_NONE, OPCODE_EXPANDER({0x23, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And r/m16 to r16")
MNEMONIC(MNEM_AND_R32_RM32, "and", PF_66, OPCODE_EXPANDER({0x23, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And r/m32 to r32")
MNEMONIC(MNEM_AND_AL_IMM8, "and", PF_NONE, OPCODE_EXPANDER({0x24, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And imm8 to AL")
MNEMONIC(MNEM_AND_AX_IMM16, "and", PF_NONE, OPCODE_EXPANDER({0x25, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And imm16 to AX")
MNEMONIC(MNEM_AND_EAX_IMM32, "and", PF_66, OPCODE_EXPANDER({0x25, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "And imm32 to EAX")

//
// ─── SEGMENT OVERRIDES (0x26, 0x2E, 0x36, 0x3E) ────────────────────────────────
//
MNEMONIC(MNEM_PFX_ES, "es", PF_NONE, OPCODE_EXPANDER({0x26, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_NONE, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "ES segment override prefix")
MNEMONIC(MNEM_PFX_CS, "cs", PF_NONE, OPCODE_EXPANDER({0x2E, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_NONE, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "CS segment override prefix")
MNEMONIC(MNEM_PFX_SS, "ss", PF_NONE, OPCODE_EXPANDER({0x36, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_NONE, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "SS segment override prefix")
MNEMONIC(MNEM_PFX_DS, "ds", PF_NONE, OPCODE_EXPANDER({0x3E, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_NONE, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "DS segment override prefix")

//
// ─── SUB (0x28 - 0x2D) ────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_SUB_RM8_R8, "sub", PF_NONE, OPCODE_EXPANDER({0x28, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract r8 from r/m8")
MNEMONIC(MNEM_SUB_RM16_R16, "sub", PF_NONE, OPCODE_EXPANDER({0x29, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract r16 from r/m16")
MNEMONIC(MNEM_SUB_RM32_R32, "sub", PF_66, OPCODE_EXPANDER({0x29, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract r32 from r/m32")
MNEMONIC(MNEM_SUB_R8_RM8, "sub", PF_NONE, OPCODE_EXPANDER({0x2A, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract r/m8 from r8")
MNEMONIC(MNEM_SUB_R16_RM16, "sub", PF_NONE, OPCODE_EXPANDER({0x2B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract r/m16 from r16")
MNEMONIC(MNEM_SUB_R32_RM32, "sub", PF_66, OPCODE_EXPANDER({0x2B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract r/m32 from r32")
MNEMONIC(MNEM_SUB_AL_IMM8, "sub", PF_NONE, OPCODE_EXPANDER({0x2C, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract imm8 from AL")
MNEMONIC(MNEM_SUB_AX_IMM16, "sub", PF_NONE, OPCODE_EXPANDER({0x2D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract imm16 from AX")
MNEMONIC(MNEM_SUB_EAX_IMM32, "sub", PF_66, OPCODE_EXPANDER({0x2D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract imm32 from EAX")

//
// ─── XOR (0x30 - 0x35) ────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_XOR_RM8_R8, "xor", PF_NONE, OPCODE_EXPANDER({0x30, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor r8 to r/m8")
MNEMONIC(MNEM_XOR_RM16_R16, "xor", PF_NONE, OPCODE_EXPANDER({0x31, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor r16 to r/m16")
MNEMONIC(MNEM_XOR_RM32_R32, "xor", PF_66, OPCODE_EXPANDER({0x31, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor r32 to r/m32")
MNEMONIC(MNEM_XOR_R8_RM8, "xor", PF_NONE, OPCODE_EXPANDER({0x32, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor r/m8 to r8")
MNEMONIC(MNEM_XOR_R16_RM16, "xor", PF_NONE, OPCODE_EXPANDER({0x33, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor r/m16 to r16")
MNEMONIC(MNEM_XOR_R32_RM32, "xor", PF_66, OPCODE_EXPANDER({0x33, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor r/m32 to r32")
MNEMONIC(MNEM_XOR_AL_IMM8, "xor", PF_NONE, OPCODE_EXPANDER({0x34, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor imm8 to AL")
MNEMONIC(MNEM_XOR_AX_IMM16, "xor", PF_NONE, OPCODE_EXPANDER({0x35, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor imm16 to AX")
MNEMONIC(MNEM_XOR_EAX_IMM32, "xor", PF_66, OPCODE_EXPANDER({0x35, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_LOGIC, (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor imm32 to EAX")

//
// ─── CMP (0x38 - 0x3D) ────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_CMP_RM8_R8, "cmp", PF_NONE, OPCODE_EXPANDER({0x38, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare r8 with r/m8")
MNEMONIC(MNEM_CMP_RM16_R16, "cmp", PF_NONE, OPCODE_EXPANDER({0x39, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare r16 with r/m16")
MNEMONIC(MNEM_CMP_RM32_R32, "cmp", PF_66, OPCODE_EXPANDER({0x39, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare r32 with r/m32")
MNEMONIC(MNEM_CMP_R8_RM8, "cmp", PF_NONE, OPCODE_EXPANDER({0x3A, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare r/m8 with r8")
MNEMONIC(MNEM_CMP_R16_RM16, "cmp", PF_NONE, OPCODE_EXPANDER({0x3B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare r/m16 with r16")
MNEMONIC(MNEM_CMP_R32_RM32, "cmp", PF_66, OPCODE_EXPANDER({0x3B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare r/m32 with r32")
MNEMONIC(MNEM_CMP_AL_IMM8, "cmp", PF_NONE, OPCODE_EXPANDER({0x3C, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare imm8 with AL")
MNEMONIC(MNEM_CMP_AX_IMM16, "cmp", PF_NONE, OPCODE_EXPANDER({0x3D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare imm16 with AX")
MNEMONIC(MNEM_CMP_EAX_IMM32, "cmp", PF_66, OPCODE_EXPANDER({0x3D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare imm32 with EAX")

//
// ─── AAS (0x3F) ───────────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_AAS, "aas", PF_NONE, OPCODE_EXPANDER({0x3F, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_NONE, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, (FLG_A | FLG_C), (FLG_A | FLG_C), FLG_NONE, (FLG_O | FLG_S | FLG_Z | FLG_P), FLG_NONE, "ASCII Adjust AL After Subtraction")

//
// ─── INC r16/r32 (0x40 - 0x47) ────────────────────────────────────────────────
//
MNEMONIC(MNEM_INC_AX, "inc", PF_NONE, OPCODE_EXPANDER({0x40, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment AX by 1")
MNEMONIC(MNEM_INC_CX, "inc", PF_NONE, OPCODE_EXPANDER({0x41, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_CX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment CX by 1")
MNEMONIC(MNEM_INC_DX, "inc", PF_NONE, OPCODE_EXPANDER({0x42, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_DX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment DX by 1")
MNEMONIC(MNEM_INC_BX, "inc", PF_NONE, OPCODE_EXPANDER({0x43, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_BX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment BX by 1")
MNEMONIC(MNEM_INC_SP, "inc", PF_NONE, OPCODE_EXPANDER({0x44, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_SP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment SP by 1")
MNEMONIC(MNEM_INC_BP, "inc", PF_NONE, OPCODE_EXPANDER({0x45, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_BP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment BP by 1")
MNEMONIC(MNEM_INC_SI, "inc", PF_NONE, OPCODE_EXPANDER({0x46, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_SI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment SI by 1")
MNEMONIC(MNEM_INC_DI, "inc", PF_NONE, OPCODE_EXPANDER({0x47, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_DI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment DI by 1")
MNEMONIC(MNEM_INC_EAX, "inc", PF_66, OPCODE_EXPANDER({0x40, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment EAX by 1")
MNEMONIC(MNEM_INC_ECX, "inc", PF_66, OPCODE_EXPANDER({0x41, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_CX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment ECX by 1")
MNEMONIC(MNEM_INC_EDX, "inc", PF_66, OPCODE_EXPANDER({0x42, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_DX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment EDX by 1")
MNEMONIC(MNEM_INC_EBX, "inc", PF_66, OPCODE_EXPANDER({0x43, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_BX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment EBX by 1")
MNEMONIC(MNEM_INC_ESP, "inc", PF_66, OPCODE_EXPANDER({0x44, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_SP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment ESP by 1")
MNEMONIC(MNEM_INC_EBP, "inc", PF_66, OPCODE_EXPANDER({0x45, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_BP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment EBP by 1")
MNEMONIC(MNEM_INC_ESI, "inc", PF_66, OPCODE_EXPANDER({0x46, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_SI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment ESI by 1")
MNEMONIC(MNEM_INC_EDI, "inc", PF_66, OPCODE_EXPANDER({0x47, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_DI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Increment EDI by 1")

//
// ─── DEC r16/r32 (0x48 - 0x4F) ────────────────────────────────────────────────
//
MNEMONIC(MNEM_DEC_AX, "dec", PF_NONE, OPCODE_EXPANDER({0x48, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement AX by 1")
MNEMONIC(MNEM_DEC_CX, "dec", PF_NONE, OPCODE_EXPANDER({0x49, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_CX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement CX by 1")
MNEMONIC(MNEM_DEC_DX, "dec", PF_NONE, OPCODE_EXPANDER({0x4A, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_DX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement DX by 1")
MNEMONIC(MNEM_DEC_BX, "dec", PF_NONE, OPCODE_EXPANDER({0x4B, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_BX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement BX by 1")
MNEMONIC(MNEM_DEC_SP, "dec", PF_NONE, OPCODE_EXPANDER({0x4C, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_SP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement SP by 1")
MNEMONIC(MNEM_DEC_BP, "dec", PF_NONE, OPCODE_EXPANDER({0x4D, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_BP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement BP by 1")
MNEMONIC(MNEM_DEC_SI, "dec", PF_NONE, OPCODE_EXPANDER({0x4E, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_SI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement SI by 1")
MNEMONIC(MNEM_DEC_DI, "dec", PF_NONE, OPCODE_EXPANDER({0x4F, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_DI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement DI by 1")
MNEMONIC(MNEM_DEC_EAX, "dec", PF_66, OPCODE_EXPANDER({0x48, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement EAX by 1")
MNEMONIC(MNEM_DEC_ECX, "dec", PF_66, OPCODE_EXPANDER({0x49, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_CX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement ECX by 1")
MNEMONIC(MNEM_DEC_EDX, "dec", PF_66, OPCODE_EXPANDER({0x4A, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_DX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement EDX by 1")
MNEMONIC(MNEM_DEC_EBX, "dec", PF_66, OPCODE_EXPANDER({0x4B, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_BX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement EBX by 1")
MNEMONIC(MNEM_DEC_ESP, "dec", PF_66, OPCODE_EXPANDER({0x4C, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_SP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement ESP by 1")
MNEMONIC(MNEM_DEC_EBP, "dec", PF_66, OPCODE_EXPANDER({0x4D, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_BP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement EBP by 1")
MNEMONIC(MNEM_DEC_ESI, "dec", PF_66, OPCODE_EXPANDER({0x4E, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_SI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement ESI by 1")
MNEMONIC(MNEM_DEC_EDI, "dec", PF_66, OPCODE_EXPANDER({0x4F, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_DI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_ARITH_NO_C, FLG_NONE, FLG_NONE, FLG_NONE, "Decrement EDI by 1")

//
// ─── PUSH r16/r32 (0x50 - 0x57) ───────────────────────────────────────────────
//
MNEMONIC(MNEM_PUSH_AX, "push", PF_NONE, OPCODE_EXPANDER({0x50, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push AX")
MNEMONIC(MNEM_PUSH_CX, "push", PF_NONE, OPCODE_EXPANDER({0x51, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_CX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push CX")
MNEMONIC(MNEM_PUSH_DX, "push", PF_NONE, OPCODE_EXPANDER({0x52, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_DX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push DX")
MNEMONIC(MNEM_PUSH_BX, "push", PF_NONE, OPCODE_EXPANDER({0x53, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_BX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push BX")
MNEMONIC(MNEM_PUSH_SP, "push", PF_NONE, OPCODE_EXPANDER({0x54, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_SP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push SP")
MNEMONIC(MNEM_PUSH_BP, "push", PF_NONE, OPCODE_EXPANDER({0x55, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_BP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push BP")
MNEMONIC(MNEM_PUSH_SI, "push", PF_NONE, OPCODE_EXPANDER({0x56, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_SI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push SI")
MNEMONIC(MNEM_PUSH_DI, "push", PF_NONE, OPCODE_EXPANDER({0x57, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_DI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push DI")
MNEMONIC(MNEM_PUSH_EAX, "push", PF_66, OPCODE_EXPANDER({0x50, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push EAX")
MNEMONIC(MNEM_PUSH_ECX, "push", PF_66, OPCODE_EXPANDER({0x51, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_CX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push ECX")
MNEMONIC(MNEM_PUSH_EDX, "push", PF_66, OPCODE_EXPANDER({0x52, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_DX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push EDX")
MNEMONIC(MNEM_PUSH_EBX, "push", PF_66, OPCODE_EXPANDER({0x53, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_BX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push EBX")
MNEMONIC(MNEM_PUSH_ESP, "push", PF_66, OPCODE_EXPANDER({0x54, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_SP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push ESP")
MNEMONIC(MNEM_PUSH_EBP, "push", PF_66, OPCODE_EXPANDER({0x55, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_BP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push EBP")
MNEMONIC(MNEM_PUSH_ESI, "push", PF_66, OPCODE_EXPANDER({0x56, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_SI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push ESI")
MNEMONIC(MNEM_PUSH_EDI, "push", PF_66, OPCODE_EXPANDER({0x57, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_DI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push EDI")

//
// ─── POP r16/r32 (0x58 - 0x5F) ────────────────────────────────────────────────
//
MNEMONIC(MNEM_POP_AX, "pop", PF_NONE, OPCODE_EXPANDER({0x58, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop AX")
MNEMONIC(MNEM_POP_CX, "pop", PF_NONE, OPCODE_EXPANDER({0x59, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_CX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop CX")
MNEMONIC(MNEM_POP_DX, "pop", PF_NONE, OPCODE_EXPANDER({0x5A, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_DX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop DX")
MNEMONIC(MNEM_POP_BX, "pop", PF_NONE, OPCODE_EXPANDER({0x5B, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_BX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop BX")
MNEMONIC(MNEM_POP_SP, "pop", PF_NONE, OPCODE_EXPANDER({0x5C, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_SP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop SP")
MNEMONIC(MNEM_POP_BP, "pop", PF_NONE, OPCODE_EXPANDER({0x5D, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_BP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop BP")
MNEMONIC(MNEM_POP_SI, "pop", PF_NONE, OPCODE_EXPANDER({0x5E, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_SI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop SI")
MNEMONIC(MNEM_POP_DI, "pop", PF_NONE, OPCODE_EXPANDER({0x5F, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_16BIT, RF_DI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop DI")
MNEMONIC(MNEM_POP_EAX, "pop", PF_66, OPCODE_EXPANDER({0x58, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop EAX")
MNEMONIC(MNEM_POP_ECX, "pop", PF_66, OPCODE_EXPANDER({0x59, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_CX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop ECX")
MNEMONIC(MNEM_POP_EDX, "pop", PF_66, OPCODE_EXPANDER({0x5A, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_DX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop EDX")
MNEMONIC(MNEM_POP_EBX, "pop", PF_66, OPCODE_EXPANDER({0x5B, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_BX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop EBX")
MNEMONIC(MNEM_POP_ESP, "pop", PF_66, OPCODE_EXPANDER({0x5C, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_SP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop ESP")
MNEMONIC(MNEM_POP_EBP, "pop", PF_66, OPCODE_EXPANDER({0x5D, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_BP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop EBP")
MNEMONIC(MNEM_POP_ESI, "pop", PF_66, OPCODE_EXPANDER({0x5E, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_SI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop ESI")
MNEMONIC(MNEM_POP_EDI, "pop", PF_66, OPCODE_EXPANDER({0x5F, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG), OPN_ONE, SZ_32BIT, RF_DI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop EDI")

//
// ─── PUSHA/POPA (0x60 - 0x61) ─────────────────────────────────────────────────
//
MNEMONIC(MNEM_PUSHA, "pusha", PF_NONE, OPCODE_EXPANDER({0x60, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE   ), OPN_NONE, SZ_16BIT, RF_NONE, MODRM_NONE, FALSE, PROC_80186, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push All General-Purpose Registers (16-bit)")
MNEMONIC(MNEM_PUSHAD, "pushad", PF_66, OPCODE_EXPANDER({0x60, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_32BIT, RF_NONE, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push All General-Purpose Registers (32-bit)")
MNEMONIC(MNEM_POPA, "popa", PF_NONE, OPCODE_EXPANDER({0x61, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_16BIT, RF_NONE, MODRM_NONE, FALSE, PROC_80186, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop All General-Purpose Registers (16-bit)")
MNEMONIC(MNEM_POPAD, "popad", PF_66, OPCODE_EXPANDER({0x61, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_32BIT, RF_NONE, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Pop All General-Purpose Registers (32-bit)")

//
// ─── BOUND (0x62) ─────────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_BOUND_R16_M16, "bound", PF_NONE, OPCODE_EXPANDER({0x62, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80186, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Check Array Index Against Bounds (16-bit)")
MNEMONIC(MNEM_BOUND_R32_M32, "bound", PF_66, OPCODE_EXPANDER({0x62, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Check Array Index Against Bounds (32-bit)")

//
// ─── ARPL (0x63) ──────────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_ARPL_RM16_R16, "arpl", PF_NONE, OPCODE_EXPANDER({0x63, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80286, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_Z, FLG_NONE, FLG_NONE, FLG_NONE, "Adjust RPL Field of Segment Selector")

//
// ─── Jcc rel8 (0x70 - 0x7F) ───────────────────────────────────────────────────
//
MNEMONIC(MNEM_JO_REL8, "jo", PF_NONE, OPCODE_EXPANDER({0x70, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_O, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if overflow (OF=1)")
MNEMONIC(MNEM_JNO_REL8, "jno", PF_NONE, OPCODE_EXPANDER({0x71, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_O, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if not overflow (OF=0)")
MNEMONIC(MNEM_JC_REL8, "jc", PF_NONE, OPCODE_EXPANDER({0x72, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_C, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if carry (CF=1)")
MNEMONIC(MNEM_JNC_REL8, "jnc", PF_NONE, OPCODE_EXPANDER({0x73, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_C, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if not carry (CF=0)")
MNEMONIC(MNEM_JE_REL8, "je", PF_NONE, OPCODE_EXPANDER({0x74, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_Z, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if equal (ZF=1)")
MNEMONIC(MNEM_JNE_REL8, "jne", PF_NONE, OPCODE_EXPANDER({0x75, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_Z, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if not equal (ZF=0)")
MNEMONIC(MNEM_JBE_REL8, "jbe", PF_NONE, OPCODE_EXPANDER({0x76, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, (FLG_C | FLG_Z), FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if below or equal (CF=1 or ZF=1)")
MNEMONIC(MNEM_JA_REL8, "ja", PF_NONE, OPCODE_EXPANDER({0x77, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, (FLG_C | FLG_Z), FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if above (CF=0 and ZF=0)")
MNEMONIC(MNEM_JS_REL8, "js", PF_NONE, OPCODE_EXPANDER({0x78, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_S, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if sign (SF=1)")
MNEMONIC(MNEM_JNS_REL8, "jns", PF_NONE, OPCODE_EXPANDER({0x79, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_S, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if not sign (SF=0)")
MNEMONIC(MNEM_JP_REL8, "jp", PF_NONE, OPCODE_EXPANDER({0x7A, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_P, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if parity (PF=1)")
MNEMONIC(MNEM_JNP_REL8, "jnp", PF_NONE, OPCODE_EXPANDER({0x7B, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, FLG_P, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if not parity (PF=0)")
MNEMONIC(MNEM_JL_REL8, "jl", PF_NONE, OPCODE_EXPANDER({0x7C, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, (FLG_S | FLG_O), FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if less (SF!=OF)")
MNEMONIC(MNEM_JGE_REL8, "jge", PF_NONE, OPCODE_EXPANDER({0x7D, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, (FLG_S | FLG_O), FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if greater or equal (SF=OF)")
MNEMONIC(MNEM_JLE_REL8, "jle", PF_NONE, OPCODE_EXPANDER({0x7E, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, (FLG_Z | FLG_S | FLG_O), FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if less or equal (ZF=1 or SF!=OF)")
MNEMONIC(MNEM_JG_REL8, "jg", PF_NONE, OPCODE_EXPANDER({0x7F, 0x00}), ENC_IMM, OPS_EXPANDER(OPS_REL8), OPN_ONE, SZ_8BIT, RF_NONE, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_REL8, X_NONE, EX_NONE, (FLG_Z | FLG_S | FLG_O), FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump short if greater (ZF=0 and SF=OF)")

//
// ─── IMMEDIATE GROUP 1 (0x80 - 0x83) ──────────────────────────────────────────
//
MNEMONIC(MNEM_ADD_RM8_IMM8, "add", PF_NONE, OPCODE_EXPANDER({0x80, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_IMM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_0, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add imm8 to r/m8")
MNEMONIC(MNEM_OR_RM8_IMM8, "or", PF_NONE, OPCODE_EXPANDER({0x80, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_IMM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_1, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_LOGIC), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Or imm8 to r/m8")
MNEMONIC(MNEM_ADC_RM8_IMM8, "adc", PF_NONE, OPCODE_EXPANDER({0x80, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_IMM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_2, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add with carry imm8 to r/m8")
MNEMONIC(MNEM_SBB_RM8_IMM8, "sbb", PF_NONE, OPCODE_EXPANDER({0x80, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_IMM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_3, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_C, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract with borrow imm8 from r/m8")
MNEMONIC(MNEM_AND_RM8_IMM8, "and", PF_NONE, OPCODE_EXPANDER({0x80, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_IMM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_4, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_LOGIC), (FLG_O | FLG_C), FLG_A, FLG_NONE, "And imm8 to r/m8")
MNEMONIC(MNEM_SUB_RM8_IMM8, "sub", PF_NONE, OPCODE_EXPANDER({0x80, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_IMM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_5, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Subtract imm8 from r/m8")
MNEMONIC(MNEM_XOR_RM8_IMM8, "xor", PF_NONE, OPCODE_EXPANDER({0x80, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_IMM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_6, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_LOGIC), (FLG_O | FLG_C), FLG_A, FLG_NONE, "Xor imm8 to r/m8")
MNEMONIC(MNEM_CMP_RM8_IMM8, "cmp", PF_NONE, OPCODE_EXPANDER({0x80, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_IMM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_7, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Compare r/m8 with imm8")
// ... (0x81 is the 16/32-bit version of 0x80) ...
MNEMONIC(MNEM_ADD_RM16_IMM16, "add", PF_NONE, OPCODE_EXPANDER({0x81, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_IMM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_0, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add imm16 to r/m16")
MNEMONIC(MNEM_ADD_RM32_IMM32, "add", PF_66, OPCODE_EXPANDER({0x81, 0x00}), ENC_MODRM, OPS_RM32_IMM32, OPN_TWO, SZ_32BIT, RF_NONE, MODRM_0, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add imm32 to r/m32")
// ... (and so on for 0x81 /1 through /7) ...
// ... (0x83 is the sign-extended imm8 version) ...
MNEMONIC(MNEM_ADD_RM16_IMM8, "add", PF_NONE, OPCODE_EXPANDER({0x83, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_IMM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_0, TRUE, PROC_80186, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, FLG_ALL, FLG_NONE, FLG_NONE, FLG_NONE, "Add sign-extended imm8 to r/m16")



//
// ─── MOV (0x88 - 0x8B: Reg/Mem; 0x8C-0x8E: Segment; 0xA0-0xA3: Accumulator) ──
//
// 0x88: MOV r/m8, r8
MNEMONIC(MNEM_MOV_RM8_R8, "mov", PF_NONE, OPCODE_EXPANDER({0x88, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM8_R8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move r8 to r/m8")
// 0x89: MOV r/m16, r16
MNEMONIC(MNEM_MOV_RM16_R16, "mov", PF_NONE, OPCODE_EXPANDER({0x89, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move r16 to r/m16")
// 0x89: MOV r/m32, r32 (386+)
MNEMONIC(MNEM_MOV_RM32_R32, "mov", PF_66, OPCODE_EXPANDER({0x89, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_R16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move r32 to r/m32")
// 0x8A: MOV r8, r/m8
MNEMONIC(MNEM_MOV_R8_RM8, "mov", PF_NONE, OPCODE_EXPANDER({0x8A, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R8_RM8), OPN_TWO, SZ_8BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move r/m8 to r8")
// 0x8B: MOV r16, r/m16
MNEMONIC(MNEM_MOV_R16_RM16, "mov", PF_NONE, OPCODE_EXPANDER({0x8B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move r/m16 to r16")
// 0x8B: MOV r32, r/m32 (386+)
MNEMONIC(MNEM_MOV_R32_RM32, "mov", PF_66, OPCODE_EXPANDER({0x8B, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_R16_RM16), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move r/m32 to r32")

// NOTE: 0x8C and 0x8E (Segment register moves) are complex and often handle 
// segment registers in the MODRM byte, which you may need to handle separately.

// 0x8C: MOV r/m16, Sreg
MNEMONIC(MNEM_MOV_RM16_SEG, "mov", PF_NONE, OPCODE_EXPANDER({0x8C, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16_SEG), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move segment register to r/m16")
// 0x8C: MOV r/m32, Sreg (386+)
MNEMONIC(MNEM_MOV_RM32_SEG, "mov", PF_66, OPCODE_EXPANDER({0x8C, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM32_SEG), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move segment register to r/m32")

// 0x8E: MOV Sreg, r/m16
MNEMONIC(MNEM_MOV_SEG_RM16, "mov", PF_NONE, OPCODE_EXPANDER({0x8E, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_SEG_RM16), OPN_TWO, SZ_16BIT, RF_NONE, MODRM_NONE, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move r/m16 to segment register")
// 0x8E: MOV Sreg, r/m32 (386+)
MNEMONIC(MNEM_MOV_SEG_RM32, "mov", PF_66, OPCODE_EXPANDER({0x8E, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_SEG_RM32), OPN_TWO, SZ_32BIT, RF_NONE, MODRM_NONE, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move r/m32 to segment register")


// 0xA0: MOV AL, moffs8 (Direct address to AL)
MNEMONIC(MNEM_MOV_AL_MOFFS8, "mov", PF_NONE, OPCODE_EXPANDER({0xA0, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_REG_MOFFS8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move moffs8 to AL")
// 0xA1: MOV AX, moffs16 (Direct address to AX)
MNEMONIC(MNEM_MOV_AX_MOFFS16, "mov", PF_NONE, OPCODE_EXPANDER({0xA1, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_REG_MOFFS16), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move moffs16 to AX")
// 0xA1: MOV EAX, moffs32 (Direct address to EAX)
MNEMONIC(MNEM_MOV_EAX_MOFFS32, "mov", PF_66, OPCODE_EXPANDER({0xA1, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_REG_MOFFS32), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move moffs32 to EAX")

// 0xA2: MOV moffs8, AL (AL to Direct address)
MNEMONIC(MNEM_MOV_MOFFS8_AL, "mov", PF_NONE, OPCODE_EXPANDER({0xA2, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_MOFFS8_REG), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move AL to moffs8")
// 0xA3: MOV moffs16, AX (AX to Direct address)
MNEMONIC(MNEM_MOV_MOFFS16_AX, "mov", PF_NONE, OPCODE_EXPANDER({0xA3, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_MOFFS16_REG), OPN_TWO, SZ_16BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move AX to moffs16")
// 0xA3: MOV moffs32, EAX (EAX to Direct address)
MNEMONIC(MNEM_MOV_MOFFS32_EAX, "mov", PF_66, OPCODE_EXPANDER({0xA3, 0x00}), ENC_DIRECT, OPS_EXPANDER(OPS_MOFFS32_REG), OPN_TWO, SZ_32BIT, RF_AX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_WRITE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move EAX to moffs32")

// 0xB0-0xB7: MOV r8, imm8 (Byte-sized moves)
MNEMONIC(MNEM_MOV_AL_IMM8, "mov", PF_NONE, OPCODE_EXPANDER({0xB0, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_AX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm8 to AL")

//
// ─── MOV r/r/m, imm (0xB0 - 0xBF: Immediate to Register) ──────────────────────
//
// B0-B7: MOV r8, imm8
MNEMONIC(MNEM_MOV_CL_IMM8, "mov", PF_NONE, OPCODE_EXPANDER({0xB1, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_CX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm8 to CL")
MNEMONIC(MNEM_MOV_DL_IMM8, "mov", PF_NONE, OPCODE_EXPANDER({0xB2, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_DX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm8 to DL")
MNEMONIC(MNEM_MOV_BL_IMM8, "mov", PF_NONE, OPCODE_EXPANDER({0xB3, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_BX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm8 to BL")
MNEMONIC(MNEM_MOV_AH_IMM8, "mov", PF_NONE, OPCODE_EXPANDER({0xB4, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_SP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm8 to AH")
MNEMONIC(MNEM_MOV_CH_IMM8, "mov", PF_NONE, OPCODE_EXPANDER({0xB5, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_BP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm8 to CH")
MNEMONIC(MNEM_MOV_DH_IMM8, "mov", PF_NONE, OPCODE_EXPANDER({0xB6, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_SI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm8 to DH")
MNEMONIC(MNEM_MOV_BH_IMM8, "mov", PF_NONE, OPCODE_EXPANDER({0xB7, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM8), OPN_TWO, SZ_8BIT, RF_DI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm8 to BH")

// B8-BF: MOV r16, imm16
MNEMONIC(MNEM_MOV_CX_IMM16, "mov", PF_NONE, OPCODE_EXPANDER({0xB9, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_CX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm16 to CX")
MNEMONIC(MNEM_MOV_DX_IMM16, "mov", PF_NONE, OPCODE_EXPANDER({0xBA, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_DX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm16 to DX")
MNEMONIC(MNEM_MOV_BX_IMM16, "mov", PF_NONE, OPCODE_EXPANDER({0xBB, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_BX, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm16 to BX")
MNEMONIC(MNEM_MOV_SP_IMM16, "mov", PF_NONE, OPCODE_EXPANDER({0xBC, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_SP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm16 to SP")
MNEMONIC(MNEM_MOV_BP_IMM16, "mov", PF_NONE, OPCODE_EXPANDER({0xBD, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_BP, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm16 to BP")
MNEMONIC(MNEM_MOV_SI_IMM16, "mov", PF_NONE, OPCODE_EXPANDER({0xBE, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_SI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm16 to SI")
MNEMONIC(MNEM_MOV_DI_IMM16, "mov", PF_NONE, OPCODE_EXPANDER({0xBF, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM16), OPN_TWO, SZ_16BIT, RF_DI, MODRM_NONE, FALSE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm16 to DI")

// B8-BF: MOV r32, imm32
MNEMONIC(MNEM_MOV_ECX_IMM32, "mov", PF_66, OPCODE_EXPANDER({0xB9, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_CX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm32 to ECX")
MNEMONIC(MNEM_MOV_EDX_IMM32, "mov", PF_66, OPCODE_EXPANDER({0xBA, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_DX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm32 to EDX")
MNEMONIC(MNEM_MOV_EBX_IMM32, "mov", PF_66, OPCODE_EXPANDER({0xBB, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_BX, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm32 to EBX")
MNEMONIC(MNEM_MOV_ESP_IMM32, "mov", PF_66, OPCODE_EXPANDER({0xBC, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_SP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm32 to ESP")
MNEMONIC(MNEM_MOV_EBP_IMM32, "mov", PF_66, OPCODE_EXPANDER({0xBD, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_BP, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm32 to EBP")
MNEMONIC(MNEM_MOV_ESI_IMM32, "mov", PF_66, OPCODE_EXPANDER({0xBE, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_SI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm32 to ESI")
MNEMONIC(MNEM_MOV_EDI_IMM32, "mov", PF_66, OPCODE_EXPANDER({0xBF, 0x00}), ENC_REG_OPCODE, OPS_EXPANDER(OPS_REG_IMM32), OPN_TWO, SZ_32BIT, RF_DI, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_NONE, X_NONE, EX_IMPLICIT, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Move imm32 to EDI")

//
// ─── 0F (TWO-BYTE) OPCODES ────────────────────────────────────────────────────
//
// MNEMONIC_0F(MNEM_JE_REL16, "je", PF_NONE, OPCODE_EXPANDER({0x84, 0x00}), ENC_IMM, OPS_REL16, OPN_ONE, SZ_16BIT, RF_NONE, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_REL16, X_NONE, EX_PREFIX_0F, FLG_Z, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump near if equal (ZF=1)")
// MNEMONIC_0F(MNEM_JE_REL32, "je", PF_66, OPCODE_EXPANDER({0x84, 0x00}), ENC_IMM, OPS_REL32, OPN_ONE, SZ_32BIT, RF_NONE, MODRM_NONE, FALSE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_NONE, RL_REL32, X_NONE, EX_PREFIX_0F, FLG_Z, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Jump near if equal (ZF=1)")
// ... (and so on for JNE, J... 0x80-0x8F) ...

//
// ─── MISC / GROUP (0xFF) ──────────────────────────────────────────────────────
//
MNEMONIC(MNEM_INC_RM16, "inc", PF_NONE, OPCODE_EXPANDER({0xFF, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16), OPN_ONE, SZ_16BIT, RF_NONE, MODRM_0, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_O | FLG_S | FLG_Z | FLG_A | FLG_P), FLG_NONE, FLG_NONE, FLG_NONE, "Increment r/m16 by 1")
MNEMONIC(MNEM_INC_RM32, "inc", PF_66, OPCODE_EXPANDER({0xFF, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM32), OPN_ONE, SZ_32BIT, RF_NONE, MODRM_0, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_O | FLG_S | FLG_Z | FLG_A | FLG_P), FLG_NONE, FLG_NONE, FLG_NONE, "Increment r/m32 by 1")
MNEMONIC(MNEM_DEC_RM16, "dec", PF_NONE, OPCODE_EXPANDER({0xFF, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16), OPN_ONE, SZ_16BIT, RF_NONE, MODRM_1, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_O | FLG_S | FLG_Z | FLG_A | FLG_P), FLG_NONE, FLG_NONE, FLG_NONE, "Decrement r/m16 by 1")
MNEMONIC(MNEM_DEC_RM32, "dec", PF_66, OPCODE_EXPANDER({0xFF, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM32), OPN_ONE, SZ_32BIT, RF_NONE, MODRM_1, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_LOCK, EX_NONE, FLG_NONE, (FLG_O | FLG_S | FLG_Z | FLG_A | FLG_P), FLG_NONE, FLG_NONE, FLG_NONE, "Decrement r/m32 by 1")
MNEMONIC(MNEM_CALL_RM16, "call", PF_NONE, OPCODE_EXPANDER({0xFF, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16), OPN_ONE, SZ_16BIT, RF_NONE, MODRM_2, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Call near, r/m16")
MNEMONIC(MNEM_CALL_RM32, "call", PF_66, OPCODE_EXPANDER({0xFF, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM32), OPN_ONE, SZ_32BIT, RF_NONE, MODRM_2, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_READ, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Call near, r/m32")
// ... (and so on for /3, /4, /5, /6) ...
MNEMONIC(MNEM_PUSH_RM16, "push", PF_NONE, OPCODE_EXPANDER({0xFF, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM16), OPN_ONE, SZ_16BIT, RF_NONE, MODRM_6, TRUE, PROC_8086, ST_DOCUMENTED, MODE_REAL, MEM_RW, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push r/m16")
MNEMONIC(MNEM_PUSH_RM32, "push", PF_66, OPCODE_EXPANDER({0xFF, 0x00}), ENC_MODRM, OPS_EXPANDER(OPS_RM32), OPN_ONE, SZ_32BIT, RF_NONE, MODRM_6, TRUE, PROC_80386, ST_DOCUMENTED, MODE_PROTECTED, MEM_RW, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Push r/m32")

//
// ─── SENTINEL ─────────────────────────────────────────────────────────────────
//
MNEMONIC(MNEM_MAX, "invalid", PF_NONE, OPCODE_EXPANDER({0xFF, 0xFF}), ENC_DIRECT, OPS_EXPANDER(OPS_NONE), OPN_NONE, SZ_NONE, RF_NONE, MODRM_NONE, FALSE, PROC_ANY, ST_UNDOCUMENTED, MODE_REAL, MEM_NONE, RL_NONE, X_NONE, EX_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE, "Invalid/Sentinel")

#undef OPCODE_EXPANDER
#undef OPS_EXPANDER