#ifndef STD_TIME_H
#define STD_TIME_H
#include <STD/TYPEDEF.h>
#define CMOS_ONLY_DEFINES
#include <DRIVERS/CMOS/CMOS.h>
#undef CMOS_ONLY_DEFINES

RTC_DATE_TIME GET_DATE_TIME(U0);
U32 GET_SECONDS(RTC_DATE_TIME *dt); // 0-59
U32 GET_MINUTES(RTC_DATE_TIME *dt); // 0-59
U32 GET_HOURS(RTC_DATE_TIME *dt); // 0-24
U32 GET_WEEKDAY(RTC_DATE_TIME *dt); // 1-7. 1=sunday
U32 GET_DAY_OF_MONTH(RTC_DATE_TIME *dt); // 1-31
U32 GET_MONTH(RTC_DATE_TIME *dt); // 1-12
U32 GET_YEAR(RTC_DATE_TIME *dt); // 0-99
U32 GET_CENTURY(RTC_DATE_TIME *dt); //  19-20

#endif // STD_TIME_H