#define TAIL_LINE_COUNT 10
#include <PROGRAMS/SYS_PROGS/TSHELL/CMD/MISC.c>
#include <PROGRAMS/SYS_PROGS/TSHELL/CMD/AC97.c>
#include <PROGRAMS/SYS_PROGS/TSHELL/CMD/CD.c>
#include <PROGRAMS/SYS_PROGS/TSHELL/CMD/DIR.c>
#include <PROGRAMS/SYS_PROGS/TSHELL/CMD/TYPE.c>
#include <PROGRAMS/SYS_PROGS/TSHELL/CMD/TAIL.c>
#include <PROGRAMS/SYS_PROGS/TSHELL/CMD/COLOUR.c>
#include <PROGRAMS/SYS_PROGS/TSHELL/CMD/SLEEP.c>