#ifndef ATGL_INPUT_H
#define ATGL_INPUT_H
#include <STD/TYPEDEF.h>
#include <LIBRARIES/ATGL/ATGL_DEFS.h>

typedef enum _ATGL_INPUT_DEVICES {
    ATGL_INPUT_DEVICE_KB,
    ATGL_INPUT_DEVICE_MS,
    ATGL_INPUT_DEVICE_AMOUNT,
} ATGL_INPUT_DEVICES;

typedef struct _ATGL_INPUT_DEVICE {
    ATGL_INPUT_DEVICES type;

} ATGL_INPUT_DEVICE, PATGL_INPUT_DEVICE;

#endif // ATGL_INPUT_H