#ifndef BATSH_H
#define BATSH_H
#include <STD/TYPEDEF.h>
#include <STD/FS_DISK.h>

#define SHELL_SCRIPT_LINE_MAX_LEN 512


U0 HANDLE_COMMAND(U8 *line);

BOOLEAN RUN_BATSH_FILE(FILE *file);
BOOLEAN RUN_BATSH_SCRIPT(PU8 path);

BOOLEAN HANDLE_BATSH_LINE(PU8 line);
VOID SHELL_SET_ECHO(U8 on);
U8 SHELL_GET_ECHO(void);

#endif // BATSH_H