@echo=off
echo        _______ ____   _____ _    _ ______ _      _      
echo     /\|__   __/ __ \ / ____| |  | |  ____| |    | |     
echo    /  \  | | | |  | | (___ | |__| | |__  | |    | |     
echo   / /\ \ | | | |  | |\___ \|  __  |  __| | |    | |     
echo  / ____ \| | | |__| |____) | |  | | |____| |____| |____ 
echo /_/    \_\_|  \____/|_____/|_|  |_|______|______|______|                                                                                          
echo atOShell v0.1 Type 'help' for a list of commands.
echo Going into home
cd /HOME
dir
echo
echo Switching into ATOS system files!
cd ../ATOS
dir