echo TSHELL v0.1 Type 'help' for a list of commands.
echo See /ATOS and /PROGRAMS!
# colour 1 0 -q 

# kill the old legacy shell, it is used anymore 
kill 1 -q
@@tmp=type
# jot

# /HOME/SRC/BOOTLOADER/MAKE_VBR.SH
# ASTRAC.BIN -A /HOME/SRC/ASTRAC/CFTEST.ASM -o /A.BIN -v
# ASTRAC.BIN -A /HOME/SRC/KRNL/KRNL_NTR.ASM -o /A.BIN
# ASTRAC.BIN -A /HOME/SRC/BOOT/VBR.ASM -o /A.BIN
# ASTRAC.BIN -D /A.BIN -o /A.DASM -v
