name: Build ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y nasm make gcc gcc-multilib genisoimage cmake ninja-build

      - name: Build ISO
        run: make iso

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          body: "Automated build from commit ${{ github.sha }}"
          prerelease: false
          make_latest: true
          files: OUTPUT/ISO/atOS.iso
